import { Column } from '@/components/Column'
import { DarkModeIconButton } from '@/components/DarkModelIconButton'
import { ColumnType } from '@/utils/enums'
import { Container, Heading, SimpleGrid } from '@chakra-ui/react'
import Head from 'next/head'
import { DndProvider } from 'react-dnd'
import { HTML5Backend } from 'react-dnd-html5-backend'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading
        fontSize={{ base: '4xl', sm: '5xl', md: '6xl' }}
        fontWeight="bold"
        textAlign="center"
        bgGradient="linear(to-l, #7928CA, #FF0080)"
        bgClip="text"
        mt={4}
      >
        Kanban App
      </Heading>
      <DarkModeIconButton position="absolute" top={0} right={2}/>
      <Container maxWidth="container.lg" px={4} py={10}>
        <DndProvider backend={HTML5Backend}>
          <SimpleGrid columns={{ base: 1, md: 4}} spacing={{ base: 16, md: 4 }}>
            <Column column={ColumnType.TO_DO}/>
            <Column column={ColumnType.IN_PROGRESS}/>
            <Column column={ColumnType.BLOCKED}/>
            <Column column={ColumnType.COMPLETED}/>
          </SimpleGrid>
        </DndProvider>
      </Container>
    </>
  )
}
